export { authService } from './authService';
export { customerService } from './customerService';
export { employeeService } from './employeeService';
export { petService } from './petService';
export { addressService } from './addressService';
export { medicalProcedureService } from './medicalProcedureService';
export { medicationService } from './medicationService';
export { stockBatchService } from './stockBatchService';
export { documentService } from './documentService';
export { clinicService } from './clinicService';
export { atendimentoService } from './atendimentoService';
export { dashboardService } from './dashboardService';
export { default as api } from './api';
